## Dynamic configuration
http:
  middlewares:
    app1-header:
      headers:
        customRequestHeaders:
          Host: "appname1.project_id.region.codeengine.appdomain.cloud"
    app2-header:
      headers:
        customRequestHeaders:
          Host: "appname2.project_id.region.codeengine.appdomain.cloud"
    app3-header:
      headers:
        customRequestHeaders:
          Host: "appname3.project_id.region.codeengine.appdomain.cloud"
    stripprefixes:
      stripPrefix:
        prefixes:
          - "/app_path2"
          - "/app_path3"
        forceSlash: false
  routers:
    app1-router:
      entryPoints: ["websecure"]
      priority: 1
      rule: "Host(`traefiktest.example.com`)"
      service: "app1-service"
      middlewares:
      - "app1-header"
    app2-router:
      entryPoints: ["websecure"]
      priority: 10
      rule: "Host(`traefiktest.example.com`) && PathPrefix(`/app_path2/`)"
      service: "app2-service"
      middlewares:
      - "stripprefixes"
      - "app2-header"
    app3-router:
      entryPoints: ["websecure"]
      priority: 11
      rule: "Host(`traefiktest.example.com`) && PathPrefix(`/app_path3/`)"
      service: "app3-service"
      middlewares:
      - "stripprefixes"
      - "app3-header"

  services:
    app1-service:
      loadBalancer:
        servers:
        - url: "https://appname1.project_id.region.codeengine.appdomain.cloud/"
    app2-service:
      loadBalancer:
        servers:
        - url: "https://appname2.project_id.region.codeengine.appdomain.cloud/"
    app3-service:
      loadBalancer:
        servers:
        - url: "https://appname3.project_id.region.codeengine.appdomain.cloud/"
